name: Build Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting (if available)
        continue-on-error: true
        run: npm run lint || echo "No linting configured"

      - name: Run tests (if available)
        continue-on-error: true
        run: npm test || echo "No tests configured"

      - name: Build executable for Linux
        run: npm run build:linux

      - name: Check build output
        run: |
          ls -lh dist/
          file dist/shogun-superPeer-linux

      - name: Test executable starts
        timeout-minutes: 1
        run: |
          chmod +x dist/shogun-superPeer-linux
          ./dist/shogun-superPeer-linux &
          SERVER_PID=$!
          sleep 5
          # Check if process is still running
          if ps -p $SERVER_PID > /dev/null; then
            echo "Server started successfully"
            kill $SERVER_PID
            exit 0
          else
            echo "Server failed to start"
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-executable
          path: dist/shogun-superPeer-linux
          retention-days: 7

